### ISSUE TITLE
Create test fixtures

### ISSUE THREAD

**Issue by davidstrauss** [php-tuf/php-tuf#3]
Create a representative set of TUF test fixtures that can allow a test -- written in PHP against the PHP library -- to verify its correct operation.

We'll want several types of test fixtures:

- [ ] The happy path
- [ ] Unhappy path: expirations
- [ ] Unhappy path: untrusted keys (never trusted)
- [ ] Unhappy path: untrusted keys (replaced by rotation)
- [ ] Unhappy path: manipulated payload

This probably doesn't name every fixture we'll need, but it's a start. We should commit any Python to create the test fixtures to the repository.

**Comment by davidstrauss** [comment]
Python TUF CLI documentation: https://github.com/theupdateframework/tuf/blob/develop/docs/CLI.mda

**Comment by hestenet** [comment]
The best way to build test fixtures, given that the signed timestamp has to be unique to the repo, the snapshot has to be unique because it includes target data, and the target is supposed to track files to prevent rollback. 

It will likely be easier for an implementation side to fan out by delegating out a target level, to prevent having to track lots of stateful changes across targets. 
- [ ] Provide delegation in our test fixtures

**Comment by xjm** [comment]
For the "Happy path":
- https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#the-client-application for the timestamp of yesterday if the fixture is yesterday
- Could skip updating root metadata for the first test (expected 404) -- BUT ensure that we fail if the 404 is NOT  returned
- So: Step 0, 2, 3, 4, 5 on the above link
- (Then add a happy path for root metadata update once that's working)

**Comment by effulgentsia** [comment]
Just a note to make sure to use at least 0.13.0 (or a later release if one is available when this is done) per #29.

**Comment by davidstrauss** [comment]
As we discussed yesterday, I'm working with the Python library, not the CLI, now: https://github.com/theupdateframework/tuf/blob/develop/docs/TUTORIAL.md
