### ISSUE TITLE
What's the deal with `keyid_hash_algorthims`? Handle and document properly

### ISSUE THREAD

**Issue by xjm** [php-tuf/php-tuf#56]
In the process of working on #44 I was comparing our code (which is roughly copied from the Python implementation) to [the spec for the document formats](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats).

According to the code, the `KeyDB` is being created directly out of the root metadata file. However, the spec does not include any mention of `keyid_hash_algorithms`. It seems to be something that's been generated by the Python CLI and is expected by the Python implementation without being in the spec.

In the `1.root.json` fixture, the key data looks like this:
```
  "keys": {
   "044ab30128013448339c79e387b4a47e8aa09e873cd9514763fbeb7610b814af": {
    "keyid_hash_algorithms": [
     "sha256",
     "sha512"
    ],
    "keytype": "ed25519",
    "keyval": {
     "public": "b9bf01ba9353b7271c1ede5ef2c48cccc0823fbcbd516a11f70864920070a326"
    },
    "scheme": "ed25519"
   },
```

I was confused as to why the algorithms were SHA 256 and 512 when we we only support Ed25519. @mbaynton suggested that it's used to create a single checksum hash of the whole key (including the signature _and_ all the associated metadata).

We should figure out why this difference from the spec exists, document it, and maybe submit an issue upstream?

**Comment by xjm** [comment]
Could use feedback from @davidstrauss  as well on this.

**Comment by davidstrauss** [comment]
>  confused as to why the algorithms were SHA 256 and 512 when we we only support Ed25519.

These serve different roles in the design and complement each other; the places where TUF uses SHA are separate from the places where TUF uses Ed25519 (or alternatives like RSA/ECDSA). The SHA-2 hashes (SHA-256 and SHA-512) create secure content digests for validating that content matches a known, trusted digest. An algorithm like Ed25519 supports asymmetric signing algorithm that allows a private keyholder to provide proof that signed content hasn't varied since they signed it.

In simile form: `symmetric encryption : asymmetric encryption :: hashes : signing`

In symmetric encryption and hashes (including HMAC), both authorized parties have access to the same secrets (though there may be no secrets in the hashing case). In asymmetric encryption and signing, only one party has a private key. In a sense, you could sign instead of hash for many cases, but it's unnecessary when you can bundle a hash into another trusted file (which is signed or otherwise assumed to be trustworthy).

In the case of TUF, the hash for the `keyid` should be a hexdigest of the SHA-256 hash of the canonical representation for the key (as specified in the spec). We'll definitely need to implement that. I suspect the support in the Python for SHA-512 is extraneous to the spec. We did a similar thing with PHP-Signify, where we have support for SHA-256 and SHA-512, even though the documented behavior (closest to a Signify spec) only specified one, IIRC.

The TUF spec specifies SHA-256, so we should use that and probably ignore support for SHA-512 in the Python. We will need SHA-256 to implement TUF, but SHA-256 is broadly available in PHP.

**Comment by davidstrauss** [comment]
This thread on the TUF mailing list confirms the assumptions in my earlier comment: https://groups.google.com/g/theupdateframework/c/dnzfemvbynY/m/kJ7xPqCSBgAJ

Specifically, it confirms that it's part of the Python reference implementation but extraneous to the spec (though not in conflict with it).

**Comment by joshuagl** [comment]
Yes, this is an artefact of the reference implementation. See theupdateframework/specification#99 for pointers to discussions and a specification proposal to improve how we deal with keyids.

Please feel free to direct questions like this to the maintainers in [#tuf](https://cloud-native.slack.com/archives/C8NMD3QJ3) on CNCF Slack or our [mailing list](https://groups.google.com/forum/?fromgroups#!forum/theupdateframework).

**Comment by pwolanin** [comment]
Various related (often old or outdated) issues/PRs in tuf

https://github.com/theupdateframework/tuf/commit/1a00d87f454e9294325752e838f9fa50c19d48ff

https://github.com/theupdateframework/tuf/issues/434

https://github.com/theupdateframework/tuf/pull/974/files

the python keydb - seems to not actually validate the key ID:
https://github.com/theupdateframework/tuf/blob/develop/tuf/keydb.py
